In [1]:

%matplotlib inline
import os
import numpy as np
from matplotlib import pyplot as plt, font_manager
plt.rcParams['font.family'] = 'Malgun Gothic'  # Windows

font_manager._rebuild()

In [ ]:
#1. Import the numpy package under the name np (★☆☆)
#1. np (★☆☆)라는 이름으로 numpy 패키지를 가져옵니다.
#import numpy as np

In [ ]:
#2. Print the numpy version and the configuration (★☆☆)
#2. numpy 버전과 구성을 인쇄합니다 (★☆☆)
# 버전 출력
print("NumPy version:", np.__version__)

In [ ]:
#3. Create a null vector of size 10 (★☆☆)
#3. 크기가 10 인 null 벡터를 만듭니다 (★☆☆).

null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
#4. How to find the memory size of any array (★☆☆)
#4. 임의의 어레이의 메모리 크기를 찾는 방법 (★☆☆)
arr = np.array([[1, 2, 3], [4, 5, 6]])

# 메모리 크기 확인 (바이트 단위)
print(f"메모리 크기: {arr.nbytes} bytes")

메모리 크기: 48 bytes


In [ ]:
#5. How to get the documentation of the numpy add function from the command line? (★☆☆)
#5. 명령 줄에서 numpy add 함수의 문서를 얻는 방법은 무엇입니까? (★☆☆)
#python -m pydoc numpy.add

In [ ]:
#6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
#6. 크기가 10이지만 다섯 번째 값인 1(☆☆)의 null 벡터를 만듭니다. ★
vector = np.zeros(10)

# Set the fifth value (index 4) to 1
vector[4] = 1

print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [7]:
# 7Create a vector with values ranging from 10 to 49 (★☆☆)
# 7. 10에서 49 사이의 값으로 벡터를 만듭니다(★☆☆).
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
# 8. Reverse a vector (first element becomes last) (★☆☆)
# 8. 벡터 반전 (첫 번째 요소가 마지막이 됨) (★☆☆)

# 10에서 49까지의 벡터 생성
vector = np.arange(10, 50)

# 벡터 뒤집기
reversed_vector = vector[::-1]

print(reversed_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [9]:
# 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
# 9. 0에서 8 사이의 값을 가진 3x3 행렬을 만듭니다(★☆☆).
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
# 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
# 10. [1,2,0,0,4,0]에서 0이 아닌 요소의 인덱스 찾기 (★☆☆)
arr = np.array([1, 2, 0, 0, 4, 0])

# 0이 아닌 요소의 인덱스 찾기
nonzero_indices = np.nonzero(arr)[0]

print(nonzero_indices)

[0 1 4]


In [11]:
# 11. Create a 3x3 identity matrix (★☆☆)
# 11. 3x3 항등 매트릭스 만들기(★☆☆)
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
# 12. Create a 3x3x3 array with random values (★☆☆)
# 12. 임의의 값으로 3x3x3 어레이 만들기(★☆☆)
array = np.random.rand(3, 3, 3)
print(array)

[[[0.8253932  0.50220338 0.67996841]
  [0.20558617 0.85928255 0.31220753]
  [0.24171917 0.25991942 0.5532293 ]]

 [[0.15142148 0.19249061 0.43559913]
  [0.21410323 0.56986853 0.19322735]
  [0.61994319 0.49019957 0.95688562]]

 [[0.45929537 0.44499478 0.19007036]
  [0.60735719 0.21401969 0.93834549]
  [0.5101502  0.70908315 0.77910148]]]


In [13]:
# 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
# 13. 임의의 값을 가진 10x10 배열을 만들고 최소값과 최대값을 찾습니다(★☆☆).
# 0.0 이상 1.0 미만의 임의의 실수로 10x10 배열 생성
array = np.random.rand(10, 10)

# 최소값과 최대값 찾기
min_val = array.min()
max_val = array.max()

print("Array:\n", array)
print("Min value:", min_val)
print("Max value:", max_val)

Array:
 [[0.48577206 0.44058974 0.45061401 0.35103136 0.8479003  0.5116162
  0.65530044 0.93400886 0.06365098 0.70684981]
 [0.35256242 0.15376224 0.33933683 0.50044493 0.35629857 0.24497754
  0.7246799  0.08147017 0.11391577 0.4151082 ]
 [0.15555633 0.02843033 0.96367208 0.55477049 0.79568184 0.94322361
  0.84699718 0.42072281 0.85345592 0.06260938]
 [0.99775788 0.38305473 0.74391981 0.52662856 0.8339313  0.83346494
  0.54144746 0.31655816 0.33591107 0.08684794]
 [0.45075633 0.11757074 0.81080375 0.39009457 0.71846073 0.49141015
  0.44659692 0.09754798 0.09495335 0.0681822 ]
 [0.8080271  0.23605209 0.69771232 0.54271111 0.62768475 0.19536699
  0.23172778 0.5175786  0.2071297  0.14262123]
 [0.05775537 0.54464734 0.82288393 0.3958014  0.82835516 0.74948073
  0.77836058 0.35416862 0.89800078 0.82177086]
 [0.61298874 0.46243557 0.74761261 0.42937402 0.10483512 0.92970624
  0.03879827 0.78298213 0.57284348 0.60704165]
 [0.94203918 0.96472529 0.24535569 0.45466445 0.20314713 0.17500185
  0.3

In [14]:
# 14. Create a random vector of size 30 and find the mean value (★☆☆)
# 14. 크기가 30인 랜덤 벡터를 만들고 평균값(★☆☆)을 찾습니다.
# 크기 30의 랜덤 벡터 생성 (0.0 이상 1.0 미만 실수)
vector = np.random.rand(30)

# 평균값 계산
mean_value = vector.mean()

print("Vector:\n", vector)
print("Mean value:", mean_value)

Vector:
 [0.6278055  0.17652991 0.59757438 0.83093841 0.30657264 0.02644186
 0.50544099 0.33215059 0.9997978  0.16215692 0.21056275 0.24345268
 0.3167989  0.88727407 0.3680602  0.32917208 0.57715779 0.84638781
 0.87065425 0.25253303 0.72771695 0.84867942 0.64343225 0.62341278
 0.7111131  0.33900271 0.91041023 0.66838194 0.72766184 0.66730452]
Mean value: 0.5444859437242253


In [15]:
# 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
# 15. 테두리에 1, 내부에 0이 있는 2D 어레이 만들기(★☆☆)
# 5x5 배열 생성, 모든 값을 1로 초기화
array = np.ones((5, 5), dtype=int)

# 내부(1부터 -1까지)를 0으로 설정
array[1:-1, 1:-1] = 0

print(array)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [ ]:
# 16. How to add a border (filled with 0's) around an existing array? (★☆☆)
# 16. 기존 배열 주위에 테두리 (0으로 채워짐)를 추가하는 방법은 무엇입니까? (★☆☆)

In [17]:
# 17. What is the result of the following expression? (★☆☆)
# 17. 다음 표현의 결과는 무엇입니까? (★☆☆)
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [18]:
# 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
# 18. 대각선 바로 아래에 값이 1,2,3,4인 5x5 행렬을 만듭니다(★☆☆).
# 대각선 아래(-1)에 [1, 2, 3, 4] 배치
matrix = np.diag([1, 2, 3, 4], k=-1)

print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [19]:
# 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
# 19. 8x8 매트릭스를 만들고 바둑판 패턴으로 채웁니다(★☆☆).
# 8x8 배열 생성, 초기값 0
chessboard = np.zeros((8, 8), dtype=int)

# 바둑판 패턴: 짝수 행은 홀수 열에 1, 홀수 행은 짝수 열에 1
chessboard[1::2, ::2] = 1  # 홀수 행, 짝수 열
chessboard[::2, 1::2] = 1  # 짝수 행, 홀수 열

print(chessboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [21]:
# 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
# 20. (6,7,8) 모양 배열을 고려할 때 100번째 요소의 인덱스 (x,y,z)는 무엇입니까? (★☆☆)
# 배열 shape
shape = (6, 7, 8)

# 0-based 인덱스 기준으로 100번째 요소 → index 99
index = np.unravel_index(99, shape)

print("Index of 100th element:", index)

Index of 100th element: (np.int64(1), np.int64(5), np.int64(3))


In [22]:
# 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
# 21. tile 함수를 사용하여 바둑판 8x8 행렬 만들기(★☆☆)
# 2x2 바둑판 블록 생성
pattern = np.array([[0, 1],
                    [1, 0]])

# 2x2 패턴을 4x4번 반복 → 8x8 바둑판 완성
chessboard = np.tile(pattern, (4, 4))

print(chessboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [24]:
# 22. Normalize a 5x5 random matrix (★☆☆)
# 22. 5x5 랜덤 매트릭스 정규화(★☆☆)
# 5x5 랜덤 매트릭스 생성 (0~1 실수)
matrix = np.random.rand(5, 5)

# 최소값과 최대값
min_val = matrix.min()
max_val = matrix.max()

# Min-Max 정규화
normalized_matrix = (matrix - min_val) / (max_val - min_val)

print("Original matrix:\n", matrix)
print("\nMin-Max Normalized matrix:\n", normalized_matrix)

# 5x5 랜덤 매트릭스 생성 (0~1 실수)
matrix = np.random.rand(5, 5)

# 평균과 표준편차
mean = matrix.mean()
std = matrix.std()

# Z-score 정규화
z_normalized_matrix = (matrix - mean) / std

print("Original matrix:\n", matrix)
print("\nZ-score Normalized matrix:\n", z_normalized_matrix)

Original matrix:
 [[0.56984761 0.46540613 0.95741727 0.93013635 0.52092271]
 [0.14618779 0.12512065 0.93744505 0.37336793 0.34444629]
 [0.40836003 0.56308797 0.64895035 0.91798729 0.22499335]
 [0.09406055 0.50584995 0.84875713 0.25584423 0.09812057]
 [0.30568973 0.83473213 0.39303613 0.5503376  0.22818318]]

Min-Max Normalized matrix:
 [[0.55108977 0.43011836 1.         0.96840134 0.49442154]
 [0.06037741 0.03597598 0.97686678 0.3235133  0.29001424]
 [0.36404358 0.54326029 0.64271209 0.95432944 0.15165551]
 [0.         0.47696322 0.87414224 0.18738914 0.0047026 ]
 [0.24512368 0.85789751 0.34629437 0.52849192 0.15535018]]
Original matrix:
 [[0.93558563 0.23295928 0.61046128 0.15576175 0.66827938]
 [0.19342282 0.31576876 0.23511355 0.37480052 0.16874831]
 [0.92020853 0.62421443 0.13994116 0.25141589 0.83071834]
 [0.33244534 0.00747843 0.1726736  0.47239571 0.46359671]
 [0.16736209 0.6073835  0.97945716 0.76987994 0.83975508]]

Z-score Normalized matrix:
 [[ 1.63958089 -0.77659099  0.5215

In [26]:
# 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
# 23. 색상을 4개의 부호 없는 바이트(RGBA)로 설명하는 사용자 정의 dtype을 만듭니다(★☆☆).
# RGBA 각각 uint8 (0~255) 4바이트로 구성된 구조체 dtype 정의
color_dtype = np.dtype([
    ('R', np.uint8),
    ('G', np.uint8),
    ('B', np.uint8),
    ('A', np.uint8)
])

# 예시로 크기 3짜리 배열 생성
colors = np.array([
    (255, 0, 0, 255),    # 빨강, 불투명
    (0, 255, 0, 128),    # 초록, 반투명
    (0, 0, 255, 0)       # 파랑, 완전투명
], dtype=color_dtype)

print(colors)
print("첫 번째 색의 R 값:", colors[0]['R'])

[(255,   0,   0, 255) (  0, 255,   0, 128) (  0,   0, 255,   0)]
첫 번째 색의 R 값: 255


In [27]:
# 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)
# 24. 5x3 행렬에 3x2 행렬(실수 행렬 곱)을 곱합니다(★☆☆)
# 5x3 행렬 생성 (예: 랜덤 실수)
A = np.random.rand(5, 3)

# 3x2 행렬 생성 (예: 랜덤 실수)
B = np.random.rand(3, 2)

# 행렬 곱
C = np.dot(A, B)  # 또는 C = A @ B

print("A (5x3):\n", A)
print("\nB (3x2):\n", B)
print("\nA @ B (5x2):\n", C)

A (5x3):
 [[0.32291465 0.0158567  0.58898141]
 [0.28399607 0.85914793 0.32176743]
 [0.78836108 0.84268602 0.65925441]
 [0.24481067 0.18148333 0.01760991]
 [0.28136134 0.4861305  0.99401049]]

B (3x2):
 [[0.25010212 0.20580871]
 [0.02898443 0.90248429]
 [0.06534819 0.47203314]]

A @ B (5x2):
 [[0.11971011 0.35878781]
 [0.11695685 0.98570126]
 [0.26467664 1.23395241]
 [0.06763864 0.22248248]
 [0.14941608 0.96583765]]


In [28]:
# 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
# 25. 1D 어레이가 주어지면 3에서 8 사이의 모든 요소를 무효화합니다. (★☆☆)
arr = np.array([1, 4, 6, 2, 8, 10, 3, 9], dtype=float)

# 3 이상 8 이하 요소를 np.nan으로 무효화
arr[(arr >= 3) & (arr <= 8)] = np.nan

print(arr)

[ 1. nan nan  2. nan 10. nan  9.]


In [29]:
# 26. What is the output of the following script? (★☆☆)
# 26. 다음 스크립트의 출력은 무엇입니까? (★☆☆)
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [ ]:
# 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
# 27. 정수 벡터 Z를 고려하면 다음 식 중 어떤 것이 유효합니까? (★☆☆)
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

In [30]:
# 28. What are the result of the following expressions? (★☆☆)
# 28. 다음 표현의 결과는 무엇입니까? (★☆☆)
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


C:\Users\user\AppData\Local\Temp\ipykernel_14940\1533695693.py:3: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\user\AppData\Local\Temp\ipykernel_14940\1533695693.py:4: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\user\AppData\Local\Temp\ipykernel_14940\1533695693.py:5: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


In [31]:
# 29. How to round away from zero a float array ? (★☆☆)
# 29. float 배열을 0에서 반올림하는 방법은 무엇입니까? (★☆☆)
arr = np.array([1.7, 2.3, -1.4, -2.6])

rounded = np.round(arr)

print(rounded)  # [ 2.  2. -1. -3.]

[ 2.  2. -1. -3.]


In [32]:
# 30. How to find common values between two arrays? (★☆☆)
# 30. 두 어레이 간의 공통 값을 찾는 방법은 무엇입니까? (★☆☆)
a = np.array([1, 2, 3, 4, 5])
b = np.array([3, 4, 5, 6, 7])

common = np.intersect1d(a, b)

print("공통 값:", common)

공통 값: [3 4 5]


In [ ]:
# 31. How to ignore all numpy warnings (not recommended)? (★☆☆)
# 31. 모든 numpy 경고를 무시하는 방법 (권장하지 않음)? (★☆☆)
#numpy.seterr로 수치 연산 경고 무시

# 모든 수치 연산 경고 무시 (divide, over, under, invalid)
np.seterr(all='ignore')

#warnings 모듈로 모든 경고 무시 (더 광범위)
import warnings
warnings.filterwarnings('ignore')

In [33]:
# 32. Is the following expressions true? (★☆☆)
# 32. 다음 표현이 사실입니까? (★☆☆)
mm = (np.sqrt(-1) == np.emath.sqrt(-1))
print(mm)

False


C:\Users\user\AppData\Local\Temp\ipykernel_14940\3090059825.py:3: RuntimeWarning: invalid value encountered in sqrt
  mm = (np.sqrt(-1) == np.emath.sqrt(-1))


In [34]:
# 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)
# 33. 어제, 오늘, 내일의 날짜는 어떻게 얻나요? (★☆☆)
from datetime import datetime, timedelta

today = datetime.today().date()
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)

print("어제:", yesterday)
print("오늘:", today)
print("내일:", tomorrow)

어제: 2025-07-09
오늘: 2025-07-10
내일: 2025-07-11


In [37]:
# 34. How to get all the dates corresponding to the month of July 2016? (★★☆)
# 34. 2016 년 7 월에 해당하는 모든 날짜를 얻는 방법은 무엇입니까? (★★☆)
from datetime import datetime, timedelta

start_date = datetime(2016, 7, 1)
end_date = datetime(2016, 7, 31)

delta = end_date - start_date

dates = [start_date + timedelta(days=i) for i in range(delta.days + 1)]

for d in dates:
    print(d.date())

2016-07-01
2016-07-02
2016-07-03
2016-07-04
2016-07-05
2016-07-06
2016-07-07
2016-07-08
2016-07-09
2016-07-10
2016-07-11
2016-07-12
2016-07-13
2016-07-14
2016-07-15
2016-07-16
2016-07-17
2016-07-18
2016-07-19
2016-07-20
2016-07-21
2016-07-22
2016-07-23
2016-07-24
2016-07-25
2016-07-26
2016-07-27
2016-07-28
2016-07-29
2016-07-30
2016-07-31


In [39]:
# 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
# 35. ((A+B)*(-A/2))를 (사본 없이) 제자리에서 계산하는 방법은 무엇입니까? (★★☆)
A = np.array([1., 2., 3.])
B = np.array([4., 5., 6.])

# 1) A에 (A + B)를 in-place로 저장
np.add(A, B, out=A)   # A = A + B

# 2) A에 (-original_A / 2)를 곱해야 하는데, 원래 A가 사라졌으므로 원본 A를 복사해둬야 함
# 하지만 사본 없이 하려면, 이 순서로는 불가능. 따라서 다른 변수에 결과 저장을 권장.

# 대신 결과를 B에 저장하는 경우:
A_orig = A.copy()  # 원본을 잠깐 복사해야 함 (사본 없이 완전 불가능)

np.add(A_orig, B, out=B)        # B = A_orig + B
np.negative(A_orig, out=A_orig) # A_orig = -A_orig
np.divide(A_orig, 2, out=A_orig) # A_orig = -A_orig / 2
np.multiply(B, A_orig, out=B)   # B = (A + B) * (-A / 2)

print(B)  # 최종 결과

[-22.5 -42.  -67.5]


In [40]:
# 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)
# 36. 4가지 다른 방법(☆)을 사용하여 양수의 무작위 배열의 정수 부분을 추출합니다. ★★
arr = np.random.rand(5) * 10  # 0~10 사이 양수 랜덤 배열

print("원본 배열:", arr)

# 1) np.floor() - 내림하여 정수 부분 추출
int_part1 = np.floor(arr).astype(int)

# 2) np.trunc() - 0 방향으로 자르기 (양수면 floor와 같음)
int_part2 = np.trunc(arr).astype(int)

# 3) astype(int) - 타입 변환 (소수점 이하 버림)
int_part3 = arr.astype(int)

# 4) np.fix() - 0 방향으로 자르기 (np.trunc과 동일)
int_part4 = np.fix(arr).astype(int)

print("1) np.floor():", int_part1)
print("2) np.trunc():", int_part2)
print("3) astype(int):", int_part3)
print("4) np.fix():", int_part4)

원본 배열: [7.18269102 1.074279   5.12107284 3.84466956 5.82469604]
1) np.floor(): [7 1 5 3 5]
2) np.trunc(): [7 1 5 3 5]
3) astype(int): [7 1 5 3 5]
4) np.fix(): [7 1 5 3 5]


In [41]:
# 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)
# 37. 행 값이 0에서 4 사이인 5x5 행렬 만들기(★★☆)
# 방법 1: np.arange와 np.tile 사용
matrix = np.tile(np.arange(5), (5,1))

print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [42]:
# 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)
# 38. 10개의 정수를 생성하는 생성기 함수를 고려하여 이를 사용하여 배열을 구축합니다(★☆☆)
def int_generator(n):
    for i in range(n):
        yield i  # 0부터 n-1까지 정수 생성
gen = int_generator(10)  # 10개의 정수를 생성하는 생성기

arr = np.fromiter(gen, dtype=int, count=10)

print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [44]:
# 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
# 39. 0에서 1 사이의 값을 가진 크기가 10인 벡터를 만들고 둘 다 제외(★★☆)합니다.
vec = np.random.rand(10)

# 0 또는 1에 딱 맞는 값이 거의 없지만, 혹시 있을 경우 재생성
while np.any((vec == 0) | (vec == 1)):
    vec = np.random.rand(10)

print(vec)

epsilon = 1e-10
vec = np.random.uniform(low=0+epsilon, high=1-epsilon, size=10)
print(vec)

[0.52908986 0.07883696 0.35511119 0.09704053 0.61786385 0.39611926
 0.05341212 0.39032279 0.24370038 0.58158012]
[0.17315913 0.93598096 0.27551605 0.62225484 0.54664199 0.6030851
 0.05429559 0.78835661 0.49016614 0.11617622]


In [45]:
# 40. Create a random vector of size 10 and sort it (★★☆)
# 40. 크기가 10인 랜덤 벡터를 만들고 정렬합니다(★★☆).
vec = np.random.rand(10)   # 0~1 사이 랜덤 10개 생성
vec.sort()                 # in-place 정렬

print(vec)

[0.04536961 0.08532587 0.42545098 0.56797756 0.63502766 0.67874299
 0.81599563 0.84544631 0.90616703 0.95600774]


In [47]:
# 41. How to sum a small array faster than np.sum? (★★☆)
# 41. np.sum보다 빠르게 작은 배열을 합산하는 방법은 무엇입니까? (★★☆)

#배열이 매우 작을 때는 NumPy 함수 호출 오버헤드가 상대적으로 크기 때문에, Python 내장 sum()이 더 빠를 수도 있습니다.
arr = np.array([1, 2, 3, 4, 5])
result = sum(arr)  # Python 내장 sum
print(result)

#np.sum도 사실 내부적으로 np.add.reduce를 쓰지만, 직접 호출해서 차이가 있을 수 있습니다.
result = np.add.reduce(arr)
print(result)

#반복문으로 직접 합산할 때 컴파일러를 이용해 속도 개선 가능
def fast_sum(arr):
    total = 0
    for x in arr:
        total += x
    return total

arr = np.array([1, 2, 3, 4, 5])
print(fast_sum(arr))

15
15
15


In [48]:
# 42. Consider two random arrays A and B, check if they are equal (★★☆)
# 42. 두 개의 랜덤 어레이 A와 B를 고려하여 같은지 확인합니다(★★☆).

#완전히 같은 배열인지 (모든 요소가 같은지)
A = np.random.rand(5)
B = np.random.rand(5)

# 배열이 완전히 같은지 확인
are_equal = np.array_equal(A, B)

print("같은가요?", are_equal)

#부동소수점 오차를 고려해 거의 같은지 확인
are_close = np.allclose(A, B)

print("거의 같은가요?", are_close)

같은가요? False
거의 같은가요? False


In [ ]:
# 43. Make an array immutable (read-only) (★★☆)
# 43. 배열을 변경 불가능하게 만들기(읽기 전용) (★★☆)
arr = np.array([1, 2, 3])
arr.flags.writeable = False  # 읽기 전용으로 설정

# 이제 변경 시도하면 에러 발생
# arr[0] = 10  # ValueError: assignment destination is read-only

In [50]:
# 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
# 44. 데카르트 좌표를 나타내는 임의의 10x2 행렬을 고려하여 극 좌표로 변환합니다. (★★☆)
# 10x2 데카르트 좌표 행렬 생성 (랜덤)
cartesian = np.random.rand(10, 2)

x = cartesian[:, 0]
y = cartesian[:, 1]

r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)  # -pi ~ pi 범위의 각도

polar = np.column_stack((r, theta))

print("데카르트 좌표:\n", cartesian)
print("극 좌표 (r, θ):\n", polar)

데카르트 좌표:
 [[0.49466232 0.87599705]
 [0.85951915 0.73294367]
 [0.49114442 0.15355535]
 [0.47022033 0.21446547]
 [0.99973208 0.4034378 ]
 [0.53016274 0.13867175]
 [0.12936072 0.7829361 ]
 [0.75851031 0.83167007]
 [0.04188084 0.96469329]
 [0.69584679 0.05087298]]
극 좌표 (r, θ):
 [[1.00601275 1.05674866]
 [1.12959267 0.70608082]
 [0.51458924 0.30301976]
 [0.51681969 0.42791153]
 [1.078066   0.38355946]
 [0.54799853 0.25583293]
 [0.79355097 1.40705055]
 [1.12561672 0.83137295]
 [0.96560196 1.52740994]
 [0.69770396 0.07297961]]


In [51]:
# 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
# 45. 크기가 10인 랜덤 벡터를 만들고 최대값을 0으로 바꿉니다. (★★☆)
vec = np.random.rand(10)
print("원본 벡터:", vec)

max_index = np.argmax(vec)   # 최대값 인덱스 찾기
vec[max_index] = 0           # 최대값을 0으로 변경

print("수정된 벡터:", vec)

원본 벡터: [0.39985274 0.56702114 0.912245   0.70215436 0.6601267  0.87690152
 0.96321751 0.84945893 0.54450906 0.84938299]
수정된 벡터: [0.39985274 0.56702114 0.912245   0.70215436 0.6601267  0.87690152
 0.         0.84945893 0.54450906 0.84938299]


In [52]:
# 46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area (★★☆)
# 46. [0,1]x[0,1] 영역을 포함하는 x 및 y 좌표로 구조화된 어레이 생성 (★★☆)
# x, y 값 생성 (예: 0.0, 0.5, 1.0)
x_vals = np.linspace(0, 1, 3)
y_vals = np.linspace(0, 1, 3)

# 격자 좌표 생성
X, Y = np.meshgrid(x_vals, y_vals)

# 구조화 dtype 정의
dt = np.dtype([('x', np.float64), ('y', np.float64)])

# 구조화 배열 생성
structured_array = np.empty(X.size, dtype=dt)

# x, y 좌표 할당
structured_array['x'] = X.ravel()
structured_array['y'] = Y.ravel()

print(structured_array)

[(0. , 0. ) (0.5, 0. ) (1. , 0. ) (0. , 0.5) (0.5, 0.5) (1. , 0.5)
 (0. , 1. ) (0.5, 1. ) (1. , 1. )]


In [53]:
# 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)
# 47. X와 Y라는 두 개의 배열이 주어지면 Cauchy 행렬 C를 구성합니다(Cij =1/(xi - yj)) (★★☆)
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])

# 브로드캐스팅을 활용해 행렬 생성
C = 1.0 / (X[:, None] - Y[None, :])

print(C)

[[-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


In [54]:
# 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)
# 48. 각 numpy 스칼라 유형에 대해 표현 가능한 최소값과 최대값을 인쇄합니다(★★☆).
int_types = [np.int8, np.int16, np.int32, np.int64,
             np.uint8, np.uint16, np.uint32, np.uint64]

float_types = [np.float16, np.float32, np.float64]

print("== 정수형 타입 ==")
for t in int_types:
    info = np.iinfo(t)
    print(f"{t.__name__:>8} : min = {info.min}, max = {info.max}")

print("\n== 부동소수점형 타입 ==")
for t in float_types:
    info = np.finfo(t)
    print(f"{t.__name__:>8} : min = {info.min}, max = {info.max}")

== 정수형 타입 ==
    int8 : min = -128, max = 127
   int16 : min = -32768, max = 32767
   int32 : min = -2147483648, max = 2147483647
   int64 : min = -9223372036854775808, max = 9223372036854775807
   uint8 : min = 0, max = 255
  uint16 : min = 0, max = 65535
  uint32 : min = 0, max = 4294967295
  uint64 : min = 0, max = 18446744073709551615

== 부동소수점형 타입 ==
 float16 : min = -65504.0, max = 65504.0
 float32 : min = -3.4028234663852886e+38, max = 3.4028234663852886e+38
 float64 : min = -1.7976931348623157e+308, max = 1.7976931348623157e+308


In [55]:
# 49. How to print all the values of an array? (★★☆)
# 49. 배열의 모든 값을 인쇄하는 방법은 무엇입니까? (★★☆)
arr = np.arange(1000)  # 큰 배열 예시

np.set_printoptions(threshold=np.inf)  # 생략 없이 모두 출력

print(arr)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

In [56]:
# 50. How to find the closest value (to a given scalar) in a vector? (★★☆)
# 50. 벡터에서 가장 가까운 값(주어진 스칼라)을 찾는 방법은 무엇입니까? (★★☆)
vec = np.array([1.2, 3.5, 7.8, 4.4, 5.0])
scalar = 4.3

# 절댓값 차이 계산
diff = np.abs(vec - scalar)

# 가장 작은 차이의 인덱스
idx = np.argmin(diff)

print(f"가장 가까운 값: {vec[idx]}, 인덱스: {idx}")

가장 가까운 값: 4.4, 인덱스: 3


In [57]:
# 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)
# 51. 위치(x,y)와 색상(r,g,b)을 나타내는 구조화된 어레이 생성 (★★☆)
# 데이터 타입 정의 (위치는 float, 색상은 0~255 범위의 uint8)
dtype = np.dtype([
    ('x', np.float64),
    ('y', np.float64),
    ('r', np.uint8),
    ('g', np.uint8),
    ('b', np.uint8)
])

# 빈 구조화 배열 생성 (예: 크기 5)
arr = np.zeros(5, dtype=dtype)

# 값 할당 예시
arr[0] = (1.0, 2.0, 255, 0, 0)  # 빨간색 위치 (1.0, 2.0)
arr[1] = (3.5, 4.5, 0, 255, 0)  # 초록색 위치 (3.5, 4.5)

print(arr)

[(1. , 2. , 255,   0, 0) (3.5, 4.5,   0, 255, 0) (0. , 0. ,   0,   0, 0)
 (0. , 0. ,   0,   0, 0) (0. , 0. ,   0,   0, 0)]


In [58]:
# 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)
# 52. 좌표를 나타내는 모양이 (100,2)인 확률 벡터를 고려하고 점별 거리를 찾습니다. (★★☆)
points = np.random.rand(100, 2)

# (100,1,2)와 (1,100,2) 빼서 각 점 쌍의 좌표 차이 계산
diff = points[:, np.newaxis, :] - points[np.newaxis, :, :]

# 유클리드 거리 계산
dist_matrix = np.sqrt(np.sum(diff**2, axis=-1))

print(dist_matrix.shape)  # (100, 100)
print(dist_matrix)

(100, 100)
[[0.         0.26326841 0.51237462 0.6168166  0.40055297 0.22619718
  0.48640331 0.12898541 0.21833429 0.24580067 0.61636686 0.35253629
  0.315649   0.51682213 0.81550217 0.41236364 0.58519361 0.76109333
  0.41585816 0.30278454 0.41328656 0.57504015 0.36060065 0.45111547
  0.26759538 0.61148613 0.17354431 0.66217619 0.76849862 0.39914047
  0.91729131 0.42630648 0.66121242 0.76689693 0.30899412 0.22750254
  0.63202501 0.09976829 0.23181717 0.75073725 0.41324955 0.71392227
  0.28388979 0.44981881 0.75135867 0.56237308 0.46352261 0.7720877
  0.26639247 0.45620034 0.32303436 0.55338355 0.50917531 0.19155617
  0.54670902 0.25205889 0.21296993 0.72160335 0.33891293 0.09652511
  0.22367205 0.3594985  0.71081766 0.29422273 0.68058711 0.23511704
  0.45822818 0.26507918 0.29736011 0.62296199 0.60376733 0.73636169
  0.47372141 0.46795675 0.05384091 0.17626528 0.52568129 0.6306503
  0.57145104 0.20668676 0.80461935 0.52939463 0.39579865 0.39021048
  0.41817248 0.54991974 0.21365618 0.64

In [59]:
# 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?
# 53. float(32비트) 배열을 정수(32비트) 배열로 변환하는 방법은 무엇입니까?
float_arr = np.array([1.7, 2.3, 3.9, -1.2], dtype=np.float32)
int_arr = float_arr.astype(np.int32)

print("float 배열:", float_arr)
print("int 배열:", int_arr)

float 배열: [ 1.7  2.3  3.9 -1.2]
int 배열: [ 1  2  3 -1]


In [ ]:
# 54. How to read the following file? (★★☆)
# 54. 다음 파일을 읽는 방법은 무엇입니까? (★★☆)
''' save filename.txt
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
'''
data = np.genfromtxt('filename.txt', delimiter=',', dtype=float)
print(data)

In [60]:
# 55. What is the equivalent of enumerate for numpy arrays? (★★☆)
# 55. numpy 배열에 대한 열거형에 해당하는 것은 무엇입니까? (★★☆)
arr = np.array([[10, 20], [30, 40]])

for idx, val in np.ndenumerate(arr):
    print(f"인덱스: {idx}, 값: {val}")

인덱스: (0, 0), 값: 10
인덱스: (0, 1), 값: 20
인덱스: (1, 0), 값: 30
인덱스: (1, 1), 값: 40


In [61]:
# 56. Generate a generic 2D Gaussian-like array (★★☆)
# 56. 일반 2D 가우스와 같은 배열 생성(★★☆)
# 파라미터
size = 100          # 배열 크기 (100x100)
mu_x, mu_y = 0, 0   # 평균 (중심)
sigma_x, sigma_y = 1, 1  # 표준편차

# 좌표 생성
x = np.linspace(-3, 3, size)
y = np.linspace(-3, 3, size)
X, Y = np.meshgrid(x, y)

# 2D 가우스 계산
G = (1/(2 * np.pi * sigma_x * sigma_y)) * np.exp(-(((X - mu_x)**2)/(2*sigma_x**2) + ((Y - mu_y)**2)/(2*sigma_y**2)))

print(G)

[[1.96412803e-05 2.35144500e-05 2.80481778e-05 3.33333738e-05
  3.94692332e-05 4.65632088e-05 5.47308141e-05 6.40952301e-05
  7.47866894e-05 8.69416146e-05 1.00701488e-04 1.16211438e-04
  1.33618519e-04 1.53069698e-04 1.74709530e-04 1.98677534e-04
  2.25105300e-04 2.54113347e-04 2.85807767e-04 3.20276721e-04
  3.57586829e-04 3.97779549e-04 4.40867600e-04 4.86831543e-04
  5.35616605e-04 5.87129835e-04 6.41237722e-04 6.97764341e-04
  7.56490145e-04 8.17151484e-04 8.79440917e-04 9.43008391e-04
  1.00746332e-03 1.07237757e-03 1.13728942e-03 1.20170832e-03
  1.26512062e-03 1.32699594e-03 1.38679431e-03 1.44397377e-03
  1.49799840e-03 1.54834663e-03 1.59451948e-03 1.63604884e-03
  1.67250526e-03 1.70350540e-03 1.72871872e-03 1.74787330e-03
  1.76076079e-03 1.76724012e-03 1.76724012e-03 1.76076079e-03
  1.74787330e-03 1.72871872e-03 1.70350540e-03 1.67250526e-03
  1.63604884e-03 1.59451948e-03 1.54834663e-03 1.49799840e-03
  1.44397377e-03 1.38679431e-03 1.32699594e-03 1.26512062e-03
  1.2017

In [62]:
# 57. How to randomly place p elements in a 2D array? (★★☆)
# 57. 2D 어레이에 p 요소를 무작위로 배치하는 방법은 무엇입니까? (★★☆
# 배열 크기 및 p 설정
m, n = 5, 5      # 5x5 배열
p = 8            # 랜덤하게 1을 넣을 개수

# 0으로 채워진 배열 생성
arr = np.zeros((m, n), dtype=int)

# 전체 인덱스 중 p개를 무작위로 선택
indices = np.random.choice(m * n, p, replace=False)

# 선택된 인덱스를 2D 인덱스로 변환
rows, cols = np.unravel_index(indices, (m, n))

# 무작위 위치에 값 배치 (예: 1)
arr[rows, cols] = 1

print(arr)

[[0 0 1 0 1]
 [1 1 0 0 0]
 [0 0 1 0 1]
 [0 1 1 0 0]
 [0 0 0 0 0]]


In [63]:
# 58. Subtract the mean of each row of a matrix (★★☆)
# 58. 행렬의 각 행의 평균을 뺍니다(★★☆)
# Example matrix
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Compute the mean of each row, keepdims=True keeps shape for broadcasting
row_means = A.mean(axis=1, keepdims=True)

# Subtract the mean from each row
result = A - row_means

print(result)

[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


In [64]:
# 59. How to sort an array by the nth column? (★★☆)
# 59. n번째 열을 기준으로 배열을 정렬하는 방법은 무엇입니까? (★★☆)
# 예제 2D 배열
arr = np.array([[1, 4, 3],
                [7, 2, 5],
                [9, 1, 8]])

n = 1  # 두 번째 열(인덱스 1)을 기준으로 정렬

# n번째 열을 기준으로 정렬된 인덱스
sorted_indices = np.argsort(arr[:, n])

# 인덱스로 정렬 적용
sorted_arr = arr[sorted_indices]

print(sorted_arr)

[[9 1 8]
 [7 2 5]
 [1 4 3]]


In [65]:
# 60. How to tell if a given 2D array has null columns? (★★☆)
# 60. 주어진 2D 어레이에 null 열이 있는지 확인하는 방법은 무엇입니까? (★★☆)
# 예시 배열 (NaN은 null 의미)
arr = np.array([[1,   np.nan, 3],
                [4,   np.nan, 6],
                [7,   np.nan, 9]])

# 각 열에 NaN만 있는지 확인
is_null_column = np.all(np.isnan(arr), axis=0)

# 하나라도 null 열이 있는지
has_null_column = np.any(is_null_column)

print("null 열이 있나요?", has_null_column)
print("null 열 위치:", np.where(is_null_column)[0])

null 열이 있나요? True
null 열 위치: [1]


In [66]:
# 61. Find the nearest value from a given value in an array (★★☆)
# 61. 배열에서 주어진 값에서 가장 가까운 값 찾기(★★☆)
arr = np.array([2.5, 8.1, 4.3, 7.7, 5.0])
target = 6.0

# 차이 계산
diff = np.abs(arr - target)

# 가장 가까운 값의 인덱스
idx = np.argmin(diff)

# 가장 가까운 값
closest = arr[idx]

print(f"배열: {arr}")
print(f"타겟: {target}")
print(f"가장 가까운 값: {closest} (인덱스: {idx})")

배열: [2.5 8.1 4.3 7.7 5. ]
타겟: 6.0
가장 가까운 값: 5.0 (인덱스: 4)


In [67]:
# 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)
# 62. 모양이 (1,3)과 (3,1)인 두 개의 배열을 고려할 때 반복자를 사용하여 합계를 계산하는 방법은 무엇입니까? (★★☆
a = np.array([[1, 2, 3]])   # shape (1, 3)
b = np.array([[4], [5], [6]])  # shape (3, 1)

# 반복자 설정: broadcasting 가능하게
with np.nditer([a, b, None]) as it:
    for x, y, z in it:
        z[...] = x + y  # 합계 저장
    result = it.operands[2]  # 세 번째는 출력 배열

print(result)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [68]:
# 63. Create an array class that has a name attribute (★★☆)
# 63. name 속성이 있는 배열 클래스 생성(★★☆)
class NamedArray(np.ndarray):
    def __new__(cls, input_array, name=""):
        # ndarray 인스턴스 생성
        obj = np.asarray(input_array).view(cls)
        # 추가 속성 설정
        obj.name = name
        return obj

    def __array_finalize__(self, obj):
        # 복사나 슬라이싱 시 name 유지
        if obj is None: return
        self.name = getattr(obj, 'name', "")
a = NamedArray([[1, 2], [3, 4]], name="my_array")
print(a)
print("이름:", a.name)

[[1 2]
 [3 4]]
이름: my_array


In [69]:
# 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)
# 64. 주어진 벡터를 고려할 때, 두 번째 벡터로 인덱싱된 각 요소에 1을 추가하는 방법(반복되는 인덱스에 주의)? (★★★)
# 초기 벡터
a = np.array([0, 0, 0, 0, 0])

# 인덱스 벡터 (중복 인덱스 포함)
idx = np.array([0, 1, 1, 3, 4, 4, 4])

# 반복되는 인덱스를 고려해서 1씩 누적 더함
np.add.at(a, idx, 1)

print(a)

[1 2 0 1 3]


In [70]:
# 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)
# 65. 인덱스 목록(I)을 기반으로 벡터(X)의 요소를 배열(F)에 누적하는 방법은 무엇입니까? (★★★)
# 예제 데이터
I = np.array([0, 1, 1, 2, 2, 2])
X = np.array([1, 2, 3, 4, 5, 6])
F = np.zeros(3, dtype=int)

# 누적 합 계산
np.add.at(F, I, X)

print(F)  # [1 5 15]

[ 1  5 15]


In [71]:
# 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)
# 66. (dtype=ubyte)의 (w,h,3) 이미지를 고려하여 고유한 색상의 수를 계산합니다.(★★☆)
# 예시: 무작위 RGB 이미지 (dtype=ubyte → np.uint8)
w, h = 100, 100
img = np.random.randint(0, 256, size=(w, h, 3), dtype=np.uint8)

# (w*h, 3) 형태로 reshape
pixels = img.reshape(-1, 3)

# 고유한 색상 계산 (행 기준)
unique_colors = np.unique(pixels, axis=0)

# 개수 출력
print("고유한 색상의 수:", len(unique_colors))

고유한 색상의 수: 9998


In [72]:
# 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)
# 67. 4차원 배열을 고려할 때 마지막 두 축의 합을 한 번에 구하는 방법은 무엇입니까? (★★★)
# 예제 4D 배열 (shape: 2x3x4x5)
arr = np.random.rand(2, 3, 4, 5)

# 마지막 두 축(2번째, 3번째 축)의 합
result = np.sum(arr, axis=(-2, -1))

print("원본 배열 shape:", arr.shape)
print("마지막 두 축 합 shape:", result.shape)

원본 배열 shape: (2, 3, 4, 5)
마지막 두 축 합 shape: (2, 3)


In [73]:
# 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices? (★★★)
# 68. 1차원 벡터 D를 고려할 때, 부분 집합 인덱스를 설명하는 동일한 크기의 벡터 S를 사용하여 D의 부분 집합 평균을 계산하는 방법은 무엇입니까? (★★★)
D = np.array([10, 20, 30, 40, 50])
S = np.array([1, 1, 2, 2, 2])

# S의 고유값이 1부터 시작한다고 가정하면,
# 그룹 번호를 0-based로 맞춤
S0 = S - 1  

# 그룹별 합 계산
sum_per_group = np.bincount(S0, weights=D)

# 그룹별 개수 계산
count_per_group = np.bincount(S0)

# 평균 계산 (그룹별 합 / 개수)
mean_per_group = sum_per_group / count_per_group

print(mean_per_group)

[15. 40.]


In [76]:
# 69. How to get the diagonal of a dot product? (★★★)
# 69. 내적의 대각선을 얻는 방법은 무엇입니까? (★★★)
#행렬곱 후 대각선 추출 (직관적이지만 비효율적)
A = np.random.rand(3, 4)
B = np.random.rand(4, 3)

C = A @ B
diag = np.diag(C)
print(diag)

#효율적으로 내적의 대각선 구하기
diag = np.einsum('ij,ji->i', A, B)
print(diag)

#np.matmul과 np.diagonal 활용
diag = np.matmul(A, B).diagonal()
print(diag)

[0.67535837 1.4916766  1.76018612]
[0.67535837 1.4916766  1.76018612]
[0.67535837 1.4916766  1.76018612]


In [77]:
# 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)
# 70. 벡터 [1, 2, 3, 4, 5]를 고려하면 각 값 사이에 3개의 연속된 0이 인터리브된 새 벡터를 만드는 방법은 무엇입니까? (★★★)
x = np.array([1, 2, 3, 4, 5])

# 새 배열 크기 계산: 원래 값 사이에 3개의 0 추가
n = len(x)
result = np.zeros(n + (n-1)*3, dtype=x.dtype)

# 원래 값들을 올바른 위치에 복사
result[::4] = x

print(result)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


In [79]:
# 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)
# 71. 차원 (5,5,3)의 배열을 고려하고 차원 (5,5)의 배열을 곱하는 방법은 무엇입니까? (★★★)
A = np.random.rand(5,5,3)
B = np.random.rand(5,5)

# B의 shape를 (5,5,1)로 확장 후 곱하기 (브로드캐스팅)
result = A * B[:, :, np.newaxis]

print(result.shape)  # (5,5,3)

#B를 각 (5,5) 위치에서 A의 3번째 축 벡터와 내적하기
B = np.random.rand(5,5,3)

# element-wise 곱 후 마지막 축 합산 (내적)
result = np.sum(A * B, axis=2)

print(result.shape)  # (5,5)

(5, 5, 3)
(5, 5)


In [80]:
# 72. How to swap two rows of an array? (★★★)
# 72. 배열의 두 행을 바꾸는 방법은 무엇입니까? (★★★)
# 예제 배열
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print("원본 배열:\n", arr)

# 0번째 행과 2번째 행을 바꾸기
arr[[0, 2]] = arr[[2, 0]]

print("행을 바꾼 배열:\n", arr)

원본 배열:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
행을 바꾼 배열:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]


In [81]:
# 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles (★★★)
# 73. 10개의 삼각형(공유 정점 포함)을 설명하는 10개의 삼중항 집합을 고려하고 모든 삼각형을 구성하는 고유한 선분 집합을 찾습니다(★★★).
# 예시: 10개의 삼각형, 각 삼각형은 3개의 정점 인덱스
triangles = np.array([
    [0, 1, 2],
    [2, 3, 4],
    [4, 5, 6],
    [6, 7, 8],
    [8, 9, 0],
    [1, 3, 5],
    [2, 4, 6],
    [3, 5, 7],
    [4, 6, 8],
    [5, 7, 9]
])

# 1. 각 삼각형에서 3개의 선분 추출
edges = np.concatenate([
    triangles[:, [0, 1]],
    triangles[:, [1, 2]],
    triangles[:, [2, 0]]
], axis=0)

# 2. 각 선분을 (작은 정점, 큰 정점) 순서로 정렬 (순서 무관하게 고유하게 만들기 위해)
edges = np.sort(edges, axis=1)

# 3. 고유한 선분만 추출
unique_edges = np.unique(edges, axis=0)

print("고유한 선분들 (각 행은 한 선분의 두 정점):")
print(unique_edges)
print("총 선분 수:", len(unique_edges))

고유한 선분들 (각 행은 한 선분의 두 정점):
[[0 1]
 [0 2]
 [0 8]
 [0 9]
 [1 2]
 [1 3]
 [1 5]
 [2 3]
 [2 4]
 [2 6]
 [3 4]
 [3 5]
 [3 7]
 [4 5]
 [4 6]
 [4 8]
 [5 6]
 [5 7]
 [5 9]
 [6 7]
 [6 8]
 [7 8]
 [7 9]
 [8 9]]
총 선분 수: 24


In [82]:
# 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)
# 74. bincount에 해당하는 정렬된 배열 C가 주어지면 np.bincount(A) == C가 되도록 배열 A를 생성하는 방법은 무엇입니까? (★★★)
C = np.array([2, 0, 3, 1])  # 예: 0은 2번, 1은 0번, 2는 3번, 3은 1번 등장

# 각 숫자를 인덱스로 생성
A = np.repeat(np.arange(len(C)), C)

print("복원된 배열 A:", A)
print("np.bincount(A):", np.bincount(A))
print("주어진 C와 같은가?:", np.bincount(A) == C)

복원된 배열 A: [0 0 2 2 2 3]
np.bincount(A): [2 0 3 1]
주어진 C와 같은가?: [ True  True  True  True]


In [ ]:
# 75. How to compute averages using a sliding window over an array? (★★★)
# 75. 배열 위의 슬라이딩 윈도우를 사용하여 평균을 계산하는 방법은 무엇입니까? (★★★)
#np.convolve를 이용한 빠른 평균 계산
window_size = 3
weights = np.ones(window_size) / window_size
result = np.convolve(arr, weights, mode='valid')

print(result)

In [ ]:
# 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)
# 76. 1차원 배열 Z를 고려하고 첫 번째 행이 (Z[0],Z[1],Z[2])이고 각 후속 행이 1씩 이동하는 2차원 배열을 만듭니다(마지막 행은 (Z[-3],Z[-2],Z[-1]) 이어야 합니다. (★★★)
from numpy.lib.stride_tricks import sliding_window_view

Z = np.array([1, 2, 3, 4, 5, 6])

result = sliding_window_view(Z, window_shape=3)
print(result)

#리스트 컴프리헨션 (간단)
result = np.array([Z[i:i+3] for i in range(len(Z) - 2)])
print(result)

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]


In [84]:
# 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)
# 77. 부울을 부정하거나 float inplace의 부호를 변경하는 방법은 무엇입니까? (★★★)

#Boolean 배열 부정 (in-place)
b = np.array([True, False, True, False])

# in-place 부정
b[:] = ~b

print(b)  # [False  True False  True]

#float 배열 부호 반전 (in-place)
f = np.array([1.0, -2.0, 3.5, -4.5])

# in-place 부호 반전
f *= -1

print(f)  # [-1.   2.  -3.5  4.5]

[False  True False  True]
[-1.   2.  -3.5  4.5]


In [85]:
# 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)
# 78. 선(2d)을 설명하는 점 P0, P1의 2세트와 점 p를 고려하여 p에서 각 선 i(P0[i], P1[i])까지의 거리를 계산하는 방법은 무엇입니까? (★★★)
def point_to_segment_distances(P0, P1, p):
    """
    P0, P1: (N, 2) 선분의 양 끝점
    p: (2,) 점 좌표
    return: (N,) 각 선분까지의 거리
    """
    v = P1 - P0            # 선분 벡터 (N,2)
    w = p - P0             # 점->선분 시작점 벡터 (N,2)

    c1 = np.einsum('ij,ij->i', w, v)    # w·v (N,)
    c2 = np.einsum('ij,ij->i', v, v)    # v·v (N,)

    t = c1 / c2                         # 투영 파라미터 (N,)
    t = np.clip(t, 0, 1)                # 0 <= t <= 1로 제한

    projection = P0 + (v.T * t).T       # 투영점 좌표 (N,2)
    dist_vec = p - projection           # 점과 투영점 벡터 (N,2)

    distances = np.linalg.norm(dist_vec, axis=1)
    return distances


# 사용 예
P0 = np.array([[0, 0], [1, 1], [2, 2]])
P1 = np.array([[1, 0], [2, 2], [3, 3]])
p = np.array([1, 2])

dist = point_to_segment_distances(P0, P1, p)
print(dist)

[2.         0.70710678 1.        ]


In [86]:
# 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)
# 79. 선(2d)을 설명하는 2개의 점 P0, P1 집합과 점 P 집합을 고려하여 각 점 j(P[j])에서 각 선 i(P0[i], P1[i])까지의 거리를 계산하는 방법은 무엇입니까? (★★★)

def points_to_segments_distances(P0, P1, P):
    """
    P0, P1: (N, 2) 선분 시작, 끝점
    P: (M, 2) 점들
    return: (M, N) 점과 선분 간 거리 행렬
    """
    N = P0.shape[0]
    M = P.shape[0]

    v = P1 - P0                     # (N, 2) 선분 벡터
    v_norm_sq = np.sum(v**2, axis=1)  # (N,) 선분 벡터 제곱합

    # 차원 맞추기: 점과 선분 쌍 만들기 위해 브로드캐스팅
    # P: (M, 1, 2), P0: (1, N, 2)
    P_expanded = P[:, np.newaxis, :]      # (M,1,2)
    P0_expanded = P0[np.newaxis, :, :]    # (1,N,2)
    v_expanded = v[np.newaxis, :, :]      # (1,N,2)
    v_norm_sq_expanded = v_norm_sq[np.newaxis, :]  # (1,N)

    w = P_expanded - P0_expanded           # (M,N,2)

    c1 = np.sum(w * v_expanded, axis=2)   # (M,N)
    t = c1 / v_norm_sq_expanded            # (M,N)
    t = np.clip(t, 0, 1)                   # 선분 내 투영 위치 제한

    projection = P0_expanded + (v_expanded * t[:, :, np.newaxis])  # (M,N,2)
    diff = P_expanded - projection        # (M,N,2)

    distances = np.linalg.norm(diff, axis=2)  # (M,N)
    return distances


# 예시
P0 = np.array([[0, 0], [1, 1]])
P1 = np.array([[1, 0], [2, 2]])
P = np.array([[1, 2], [3, 3]])

dist_mat = points_to_segments_distances(P0, P1, P)
print(dist_mat)

[[2.         0.70710678]
 [3.60555128 1.41421356]]


In [94]:
# 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary) (★★★)
# 80. 임의의 배열을 고려하고, 고정된 모양으로 지정된 요소를 중심으로 하위 파트를 추출하는 함수를 작성하십시오(필요한 경우 채우기 값으로 채우기) (★★★)
def extract_subarray(arr, center, shape, fill_value=0):
    arr = np.asarray(arr)
    ndim = arr.ndim
    
    if len(center) != ndim or len(shape) != ndim:
        raise ValueError(f"center와 shape는 배열 차원({ndim})과 같아야 합니다. "
                         f"받은 center 길이={len(center)}, shape 길이={len(shape)}")
    
    out = np.full(shape, fill_value, dtype=arr.dtype)
    src_slices = []
    dst_slices = []
    
    import builtins
    
    for i in range(ndim):
        start = center[i] - shape[i] // 2
        end = start + shape[i]
        
        arr_dim_size = arr.shape[i]
        
        print(f"dim {i}: start={start}({type(start)}), end={end}({type(end)}), arr_dim_size={arr_dim_size}({type(arr_dim_size)})")
        
        src_start = builtins.max(start, 0)
        src_end = builtins.min(end, arr_dim_size)
        
        if src_start >= arr_dim_size or src_end <= 0:
            src_start = src_end = 0
        
        dst_start = src_start - start
        dst_end = dst_start + (src_end - src_start)
        
        src_slices.append(slice(src_start, src_end))
        dst_slices.append(slice(dst_start, dst_end))
        
    out[tuple(dst_slices)] = arr[tuple(src_slices)]
    
    return out

arr = np.arange(1, 17).reshape(4,4)
center = (1, 1)
shape = (3, 3)

sub = extract_subarray(arr, center, shape, fill_value=0)
print(sub)


dim 0: start=0(<class 'int'>), end=3(<class 'int'>), arr_dim_size=4(<class 'int'>)
dim 1: start=0(<class 'int'>), end=3(<class 'int'>), arr_dim_size=4(<class 'int'>)
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]


In [95]:
# 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)
# 81. 배열 Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], 배열 R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]를 생성하는 방법을 고려하십시오. (★★★)

from numpy.lib.stride_tricks import sliding_window_view

Z = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
window_size = 4

R = sliding_window_view(Z, window_shape=window_size)
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [96]:
# 82. Compute a matrix rank (★★★)
# 82. 행렬 순위 계산 (★★★)
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

rank = np.linalg.matrix_rank(A)
print("Matrix rank:", rank)

Matrix rank: 2


In [97]:
# 83. How to find the most frequent value in an array?
# 83. 어레이에서 가장 빈번한 값을 찾는 방법은 무엇입니까?
#정수 배열에 대해 np.bincount + argmax
arr = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])

counts = np.bincount(arr)
most_frequent = np.argmax(counts)

print("가장 빈번한 값:", most_frequent)

가장 빈번한 값: 4


In [ ]:
# 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)
# 84. 임의의 10x10 행렬()에서 연속된 모든 3x3 블록을 추출합니다. ★★★
from numpy.lib.stride_tricks import sliding_window_view

# 임의의 10x10 행렬 생성
A = np.random.rand(10, 10)

# 3x3 윈도우로 슬라이딩 뷰 생성
blocks = sliding_window_view(A, (3, 3))

print("blocks.shape:", blocks.shape)

In [3]:
# 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)
# 85. Z[i,j] == Z[j,i] 가 되는 2D 배열 서브 클래스를 만듭니다.(★★★)

# 예시 행렬 생성
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("원래 행렬:\n", matrix)

# 전치 행렬 생성 (방법 1)
transposed_matrix_1 = matrix.T
print("\n전치 행렬 (방법 1):\n", transposed_matrix_1)

# 전치 행렬 생성 (방법 2)
transposed_matrix_2 = np.transpose(matrix)
print("\n전치 행렬 (방법 2):\n", transposed_matrix_2)

# 전치 행렬의 모양 출력
print("\n원래 행렬 모양:", matrix.shape)
print("전치 행렬 모양:", transposed_matrix_1.shape)


class TransposeView(np.ndarray):
    def __new__(cls, input_array):
        obj = np.asarray(input_array).view(cls)
        if obj.ndim != 2:
            raise ValueError("Input must be 2D array")
        return obj
    
    def transpose(self, *axes):
        # axes 인자가 없으면 기본 전치 (행과 열 교체)
        if axes:
            # axes가 주어지면 기본 transpose 실행 후 서브클래스로 변환
            transposed = super().transpose(*axes)
        else:
            transposed = super().transpose()
        # 전치된 결과를 같은 서브클래스로 변환해 반환
        return transposed.view(type(self))
    
    @property
    def T(self):
        return self.transpose()

# 사용 예
A = TransposeView(np.array([[1, 2, 3],
                            [4, 5, 6]]))  # 2x3 행렬

print("원본 A (2x3):\n", A)
print("전치 A.T (3x2):\n", A.T)

print("전치된 객체 타입:", type(A.T))

원래 행렬:
 [[1 2 3]
 [4 5 6]]

전치 행렬 (방법 1):
 [[1 4]
 [2 5]
 [3 6]]

전치 행렬 (방법 2):
 [[1 4]
 [2 5]
 [3 6]]

원래 행렬 모양: (2, 3)
전치 행렬 모양: (3, 2)
원본 A (2x3):
 [[1 2 3]
 [4 5 6]]
전치 A.T (3x2):
 [[1 4]
 [2 5]
 [3 6]]
전치된 객체 타입: <class '__main__.TransposeView'>


In [4]:
# 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)
# 86. 모양이 (n,n)인 p 행렬 집합과 모양이 (n,1)인 p 벡터 집합을 고려하십시오. p 행렬 곱의 합을 한 번에 계산하는 방법은 무엇입니까? (결과의 모양은 (n,1)입니다) (★★★)
# 예시 크기
p, n = 5, 3

# 임의의 데이터 생성
matrices = np.random.rand(p, n, n)   # shape (p, n, n)
vectors = np.random.rand(p, n, 1)    # shape (p, n, 1)

# 행렬 곱: 각 p번째 행렬과 벡터 곱셈
products = np.matmul(matrices, vectors)  # shape (p, n, 1)

# 결과 모두 더하기
result = np.sum(products, axis=0)  # shape (n, 1)

print("최종 결과 (shape):", result.shape)
print(result)

최종 결과 (shape): (3, 1)
[[2.54946574]
 [2.3530947 ]
 [2.87710671]]


In [5]:
# 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)
# 87. 16x16 배열을 고려할 때 블록 합계(블록 크기는 4x4)를 얻는 방법은 무엇입니까? (★★★)
# 예시 16x16 배열 생성
arr = np.arange(16*16).reshape(16, 16)

# 4x4 블록 크기
block_size = 4

# 16x16 배열을 (4,4,4,4) 형태로 reshape
blocks = arr.reshape(16//block_size, block_size, 16//block_size, block_size)

# 블록 축을 바꿔서 (4,4,4,4) -> (4,4,4,4) 유지하되 블록별 합을 위해
# 축 1과 3을 합친다 (즉, 각 4x4 블록 내 원소들 합산)
block_sums = blocks.sum(axis=(1,3))

print(block_sums)
print("결과 shape:", block_sums.shape)

[[ 408  472  536  600]
 [1432 1496 1560 1624]
 [2456 2520 2584 2648]
 [3480 3544 3608 3672]]
결과 shape: (4, 4)


In [ ]:
# 88. How to implement the Game of Life using numpy arrays? (★★★)
# 88. numpy 배열을 사용하여 Game of Life를 구현하는 방법은 무엇입니까? (★★★)
from scipy.signal import convolve2d  # 여기를 추가하세요!

def game_of_life_step(grid):
    # Define the convolution kernel for neighbor counting
    kernel = np.array([[1, 1, 1],
                       [1, 0, 1],
                       [1, 1, 1]])

    # Calculate live neighbors using convolution
    # 'wrap' mode handles periodic boundary conditions
    live_neighbors = convolve2d(grid, kernel, mode='same', boundary='wrap')

    # Create a new grid for the next generation
    new_grid = np.zeros_like(grid)

    # Apply Game of Life rules
    # Survival: Living cell with 2 or 3 neighbors stays alive
    new_grid[(grid == 1) & ((live_neighbors == 2) | (live_neighbors == 3))] = 1
    # Reproduction: Dead cell with exactly 3 neighbors becomes alive
    new_grid[(grid == 0) & (live_neighbors == 3)] = 1

    return new_grid


# 초기 상태
np.random.seed(42)
board = np.random.choice([0, 1], size=(10, 10))

# 상태 저장: 이전 10개 세대까지 추적
previous_states = []
max_generations = 100

for gen in range(max_generations):
    print(f"\n세대 {gen+1}:\n{board}")
    
    # 이전 상태와 비교해서 중복 확인
    if any(np.array_equal(board, prev) for prev in previous_states):
        print("반복 상태 또는 정지 상태에 도달했습니다. 시뮬레이션 종료.")
        break

    previous_states.append(board.copy())
    
    # 최근 10개까지만 기억
    if len(previous_states) > 10:
        previous_states.pop(0)
        
    board = game_of_life_step(board)


세대 1:
[[0 1 0 0 0 1 0 0 0 1]
 [0 0 0 0 1 0 1 1 1 0]
 [1 0 1 1 1 1 1 1 1 1]
 [0 0 1 1 1 0 1 0 0 0]
 [0 0 1 1 1 1 1 0 1 1]
 [0 1 0 1 0 1 1 0 0 0]
 [0 0 0 0 0 1 1 0 1 1]
 [1 1 0 1 0 1 1 1 0 1]
 [0 1 0 1 0 0 1 0 1 1]
 [1 1 1 1 1 1 1 1 1 0]]

세대 2:
[[0 1 0 0 0 0 0 0 0 1]
 [0 1 1 0 0 0 0 0 0 0]
 [0 1 1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [1 0 0 1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 1 1]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]]

세대 3:
[[1 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [1 0 1 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0]
 [1 1 1 0 0 0 0 0 0 1]
 [0 1 1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]

세대 4:
[[0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [1 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 1 0 0 0 0 0 0 1]
 [1 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]

세대 5:
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 

In [6]:
# 89. How to get the n largest values of an array (★★★)
# 89. 배열의 n개의 가장 큰 값을 얻는 방법(★★★)
arr = np.array([10, 3, 7, 1, 23, 9, 5])
n = 3  # 상위 n개

# 방법 1: partition (빠름, 정렬은 안 됨)
top_n = np.partition(arr, -n)[-n:]
print("Top n (정렬되지 않음):", top_n)

# 방법 2: sort (느리지만 정렬됨)
top_n_sorted = np.sort(arr)[-n:]
print("Top n (정렬됨):", top_n_sorted)

# 방법 3: argsort로 인덱스도 얻기
indices = np.argsort(arr)[-n:][::-1]
print("Top n values with indices:", arr[indices])
print("Indices:", indices)

Top n (정렬되지 않음): [ 9 10 23]
Top n (정렬됨): [ 9 10 23]
Top n values with indices: [23 10  9]
Indices: [4 0 5]


In [7]:
# 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)
# 90. 임의의 수의 벡터가 주어지면 데카르트 곱(모든 항목의 모든 조합) 을 구축합니다.★★★
# 예: 세 개의 1D 벡터
a = np.array([1, 2])
b = np.array([3, 4])
c = np.array([5, 6])

# 리스트로 묶기
arrays = [a, b, c]

# meshgrid를 이용해 좌표 그리드 생성
mesh = np.meshgrid(*arrays, indexing='ij')

# 각 좌표축을 1D로 펼친 후 쌓기
cartesian = np.stack(mesh, axis=-1).reshape(-1, len(arrays))

print(cartesian)

[[1 3 5]
 [1 3 6]
 [1 4 5]
 [1 4 6]
 [2 3 5]
 [2 3 6]
 [2 4 5]
 [2 4 6]]


In [8]:
# 91. How to create a record array from a regular array? (★★★)
# 91. 일반 배열에서 레코드 배열을 만드는 방법은 무엇입니까? (★★★)
# 일반 배열 (예: 3행 2열)
data = np.array([[1, 2],
                 [3, 4],
                 [5, 6]])

# 필드 이름과 dtype 지정 → 레코드 배열 생성
record_array = np.core.records.fromarrays(data.T, names='x, y', formats='i8, i8')

print(record_array)
print(record_array[0].x, record_array[0].y)

[(1, 2) (3, 4) (5, 6)]
1 2


C:\Users\user\AppData\Local\Temp\ipykernel_22816\3254057562.py:9: DeprecationWarning: numpy.core is deprecated and has been renamed to numpy._core. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.records.
  record_array = np.core.records.fromarrays(data.T, names='x, y', formats='i8, i8')


In [11]:
# 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)
# 92. 큰 벡터 Z를 고려하고 3가지 다른 방법() 을 사용하여 Z를 3의 거듭제곱으로 계산합니다.★★★
Z = np.random.rand(10**6)  # 큰 벡터 (예: 100만 개 원소)
Z_cube1 = Z ** 3
print(Z_cube1)

Z_cube2 = np.power(Z, 3)
print(Z_cube2)

Z_cube3 = Z * Z * Z
print(Z_cube3)


[0.09457314 0.68746992 0.0821967  ... 0.97133958 0.00344953 0.08584316]
[0.09457314 0.68746992 0.0821967  ... 0.97133958 0.00344953 0.08584316]
[0.09457314 0.68746992 0.0821967  ... 0.97133958 0.00344953 0.08584316]


In [12]:
# 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)
# 93. 형상 (8,3) 및 (2,2)의 두 배열 A와 B를 고려하십시오. B의 요소 순서에 관계없이 B의 각 행의 요소를 포함하는 A의 행을 찾는 방법은 무엇입니까? (★★★)
# A: (8, 3) 배열
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [1, 3, 2],   # 순서 다른 1,2,3
    [7, 8, 9],
    [2, 3, 4],
    [3, 4, 5],
    [1, 2, 4],
    [2, 5, 6]
])

# B: (2, 2) 배열 (찾고 싶은 두 값의 조합들)
B = np.array([
    [2, 1],   # A의 행 중 1,2를 모두 포함하는 것
    [5, 6]    # A의 행 중 5,6 포함하는 것
])

matches = []

for b in B:
    # 각 행에서 b의 모든 원소가 포함되어 있는지 확인
    mask = np.array([np.isin(b, row).all() for row in A])
    match_indices = np.where(mask)[0]
    matches.append(match_indices)

print("B의 각 행이 포함된 A의 행 인덱스:")
for i, idxs in enumerate(matches):
    print(f"B[{i}] = {B[i]} ⟶ A[{idxs}]")

B의 각 행이 포함된 A의 행 인덱스:
B[0] = [2 1] ⟶ A[[0 2 6]]
B[1] = [5 6] ⟶ A[[1 7]]


In [13]:
# 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)
# 94. 10x3 행렬을 고려하여 값이 같지 않은 행을 추출합니다(예: [2,2,3]) (★★★)
# 예시 10x3 행렬 (일부 행은 모든 값이 같음)
A = np.array([
    [1, 1, 1],   # 같은 값
    [2, 2, 3],   # 다름
    [4, 4, 4],   # 같은 값
    [5, 6, 7],   # 다름
    [8, 8, 8],   # 같은 값
    [9, 0, 9],   # 다름
    [1, 1, 2],   # 다름
    [3, 3, 3],   # 같은 값
    [4, 5, 6],   # 다름
    [7, 7, 7]    # 같은 값
])

# 행마다 모든 값이 같은지 확인
same_values = np.all(A == A[:, [0]], axis=1)  # True인 행은 모든 값이 같음

# 같지 않은 행만 선택
A_filtered = A[~same_values]

print("모든 값이 같지 않은 행들:")
print(A_filtered)

모든 값이 같지 않은 행들:
[[2 2 3]
 [5 6 7]
 [9 0 9]
 [1 1 2]
 [4 5 6]]


In [15]:
# 95. Convert a vector of ints into a matrix binary representation (★★★)
# 95. ints의 벡터를 행렬 이진 표현으로 변환(★★★)
ints = np.array([1, 2, 3, 7, 8])  # 정수 벡터
def int_to_binary_matrix(ints, width=None):
    if width is None:
        width = int(ints.max()).bit_length()  # numpy.int64 → int로 변환

    return ((ints[:, None] & (1 << np.arange(width - 1, -1, -1))) > 0).astype(int)

# 테스트 벡터
ints = np.array([1, 2, 3, 7, 8])
binary_matrix = int_to_binary_matrix(ints)

print("이진 행렬:\n", binary_matrix)

이진 행렬:
 [[0 0 0 1]
 [0 0 1 0]
 [0 0 1 1]
 [0 1 1 1]
 [1 0 0 0]]


In [16]:
# 96. Given a two dimensional array, how to extract unique rows? (★★★)
# 96. 2차원 배열이 주어지면 고유한 행을 추출하는 방법은 무엇입니까? (★★★)
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [1, 2, 3],
    [7, 8, 9]
])

unique_rows = np.unique(arr, axis=0)
print(unique_rows)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
# 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)
# 97. 2개의 벡터 A 및 B를 고려하여 inner, outer, sum 및 mul function에 해당하는 einsum을 작성하십시오.(★★★)
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
inner = np.einsum('i,i->', A, B)
print(inner)  # 1*4 + 2*5 + 3*6 = 32

outer = np.einsum('i,j->ij', A, B)
print(outer)

sum_A = np.einsum('i->', A)
print(sum_A)  # 1+2+3 = 6

mul = np.einsum('i,i->i', A, B)
print(mul)  # [1*4, 2*5, 3*6] = [4, 10, 18]

32
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
6
[ 4 10 18]


In [19]:
# 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?
# 98. 두 벡터(X,Y)로 설명되는 경로를 고려할 때 등거리 샘플을 사용하여 샘플링하는 방법은 무엇입니까? (★★★)
def equidistant_sampling(X, Y, spacing):
    # 1. 각 점 사이 거리 계산
    deltas = np.sqrt(np.diff(X)**2 + np.diff(Y)**2)
    dist = np.insert(np.cumsum(deltas), 0, 0)  # 누적 거리

    # 2. 등간격 거리 생성
    total_length = dist[-1]
    num_points = int(np.floor(total_length / spacing)) + 1
    distances = np.linspace(0, total_length, num_points)

    # 3. 보간하여 새로운 X, Y 좌표 계산
    X_sampled = np.interp(distances, dist, X)
    Y_sampled = np.interp(distances, dist, Y)

    return X_sampled, Y_sampled

# 사용 예
X = np.array([0, 1, 3, 6, 10])
Y = np.array([0, 1, 0, 1, 0])
spacing = 1.0  # 등간격 거리

X_new, Y_new = equidistant_sampling(X, Y, spacing)

print("새 좌표 X:", X_new)
print("새 좌표 Y:", Y_new)

새 좌표 X: [ 0.          0.77326828  1.69132013  2.66943573  3.6868319   4.72428016
  5.76172841  6.81725404  7.87816936  8.93908468 10.        ]
새 좌표 Y: [0.         0.77326828 0.65433993 0.16528214 0.22894397 0.57476005
 0.92057614 0.79568649 0.53045766 0.26522883 0.        ]


In [20]:
# 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)
# 99. 정수 n과 2D 배열 X가 주어지면 X에서 n도의 다항 분포에서 추출한 것으로 해석될 수 있는 행, 즉 정수만 포함하고 합이 n인 행을 선택합니다. (★★★)
def select_rows_poly_dist(X, n):
    # 1) 정수인지 확인 (소수부가 0인지)
    is_integer = np.modf(X)[0] == 0
    
    # 각 행이 모두 정수인지 (모든 열이 True인지)
    rows_are_int = np.all(is_integer, axis=1)
    
    # 2) 행의 합이 n인지
    rows_sum_n = np.sum(X, axis=1) == n
    
    # 3) 두 조건을 모두 만족하는 행 선택
    valid_rows = rows_are_int & rows_sum_n
    
    return X[valid_rows]

# 테스트 예시
X = np.array([[2, 3, 5],
              [1.0, 2.0, 3.0],
              [4, 4, 4],
              [3, 4, 3]])

n = 10

result = select_rows_poly_dist(X, n)
print(result)

[[2. 3. 5.]
 [3. 4. 3.]]


In [21]:
# 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)
# 100. 1D 배열 X의 평균에 대해 부트스트랩된 95% 신뢰 구간을 계산합니다(즉, 대체 N회를 사용하여 배열의 요소를 다시 샘플링하고 각 샘플의 평균을 계산한 다음 평균에 대한 백분위수를 계산합니다). (★★★)

def bootstrap_ci(X, N=1000, alpha=0.05, random_state=None):
    rng = np.random.default_rng(random_state)  # 재현성 위한 시드 설정 가능
    
    n = len(X)
    means = np.empty(N)
    
    for i in range(N):
        sample = rng.choice(X, size=n, replace=True)
        means[i] = np.mean(sample)
    
    lower = np.percentile(means, 100 * (alpha/2))
    upper = np.percentile(means, 100 * (1 - alpha/2))
    
    return lower, upper

# 사용 예시
X = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

ci_lower, ci_upper = bootstrap_ci(X, N=10000, alpha=0.05)
print(f"95% 신뢰구간: [{ci_lower:.3f}, {ci_upper:.3f}]")


95% 신뢰구간: [3.800, 7.300]
